### ISSUE TITLE
Fix nested anonymous parameter forwarding

### ISSUE THREAD

**Issue by ybougo** [bkuhlmann/refinements#6]
## Why
After updating to Ruby 3.3, I encountered a specific syntax error in the `refinements` gem. This issue seems to be a result of changes in the Ruby 3.3 language specifications.

## How
1. Update Ruby to version 3.3.
2. Install `refinements` gem version 11.1.2.
3. Run a Ruby application.
4. Confirm that the following error message appears:

```console
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/refinements-11.1.2/lib/refinements/ios.rb:31: anonymous block parameter is also used within block (SyntaxError)
/home/user/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/refinements-11.1.2/lib/refinements/symbols.rb:8: anonymous block parameter is also used within block (SyntaxError)
```

## Notes
- The Ruby version in use: 3.3.0
- The encountered error: `SyntaxError` present in both the `ios.rb` and `symbols.rb` files of the `refinements` gem.
- A likely cause of this issue: The recent changes in the Ruby 3.3 language specifications, which appear to prohibit the utilization of `&` as a variable name within a block.

**Comment by bkuhlmann** [comment]
Thanks for catching this. :bow: This is fixed in [Refinements 11.1.3](https://alchemists.io/projects/refinements/versions) which will work with Ruby 3.2.0 or 3.3.0. I'll have more improvements in the next week or so but, for now, you can use the latest version with out seeing the syntax errors due to this [change](https://bugs.ruby-lang.org/issues/19370#change-105842) in the Ruby syntax.
